### ISSUE TITLE
패키지 구조가 잘못된 것 같습니다

### ISSUE THREAD

**Issue by JunJaBoy** [team-aliens/DMS-Android#179]
<img width="455" alt="스크린샷 2023-01-21 00 24 30" src="https://user-images.githubusercontent.com/101160207/213735694-ced988c4-d3da-46ef-bfef-0a3b131bb46c.png">

패키지 구조가 `com.example`로 되어 있어요

**Comment by Leesin0222** [comment]
오히려 좋아
