### ISSUE TITLE
buildSrc 플러그인 의존성 중복 선언한 것 같아요

### ISSUE THREAD

**Issue by JunJaBoy** [team-aliens/DMS-Android#180]
### Describe

`KOTLIN-ANDROID`랑 `KOTLIN_ANDROID_PLUGIN`이랑 결국 동일한 플러그인인 같습니다

<img width="949" alt="스크린샷 2023-01-26 17 06 56" src="https://user-images.githubusercontent.com/101160207/214786482-786c08d7-d5dd-4d0e-aa6a-b2e69843ec61.png">
<img width="976" alt="스크린샷 2023-01-26 17 07 25" src="https://user-images.githubusercontent.com/101160207/214786467-a82bfdef-faf3-4b18-bf15-18cc40eb37ac.png">
<img width="683" alt="스크린샷 2023-01-26 17 07 05" src="https://user-images.githubusercontent.com/101160207/214786479-bb89195c-9ac7-426f-b444-3facb288d4c2.png">

**Comment by Leesin0222** [comment]
it's design system

**Comment by Leesin0222** [comment]
so, diffrent

**Comment by Leesin0222** [comment]
I understand that the design system is different because I was going to take it out as a library later.

**Comment by JunJaBoy** [comment]
oh, I see. I always rooting for DMS, the best school service ever
