### ISSUE TITLE
불필요한 composable 변수 선언 및 recomposition시 반복적인 초기화로 인한 성능 저하 우려..

### ISSUE THREAD

**Issue by JunJaBoy** [team-aliens/DMS-Android#200]
### Describe

# 문제 상황
<img width="511" alt="image" src="https://user-images.githubusercontent.com/101160207/219411848-44f26a2b-6a87-4e25-abbd-79b67eeff4bc.png">

위 코드는 NoticeDetailScreen에서 발췌한 코드이며, Screen 코드의 전반적으로 이와 비슷한 유형의 코드가 존재합니다. 예상하기로는 이 변수들이 모두 사용되는 경우는 존재하지 않아서 불필요한 메모리 할당이 발생하고, recomposition시 state가 아닌 이 변수들을 계속해서 초기화하기 때문에 성능 저하가 발생하지 않을까 합니다. 

# 해결 방법 제안
## 1 (Best)
각 변수들이 참조하는 원본 리소스를 각 상황에 맞는 분기가 발생했을 때, 그제서야 참조하게 하여 불필요한 메모리 할당을 줄일 수 있습니다.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/101160207/219412575-54fc5f13-d5b1-41c0-9f06-bec47ac8e2a9.png">

## 2 (Better)
각 변수들이 참조하고 있는 원본 스트링 리소스를 코드상으로 사용하기 위해, Hilt 모듈에서 ApplicationContext를 제공해 주는 새로운 컴포넌트(예: StringResourceManager)를 구현하여 재사용되는 리소스를 전역적으로 사용하도록 합니다.

## 3 (Good)
각 변수들을 State로 선언한 뒤, remember로 delegate(또는 일반 선언)하여 각 변수의 초기화를 막습니다.

**Comment by JunJaBoy** [comment]
@aahspringaa4 @Leesin0222 @limsaehyun @Tmdhoon2 @chlgkdms

**Comment by limsaehyun** [comment]
1번 방법에 동의합니다.
백엔드팀과 회의하여 명시해준 API 문서에 따라서 상황에 맞게 에러 핸들링을 하는게 맞다고 생각합니다.
또한 에러 핸들링 중에서도 공통적으로 처리되어야 하는 로직 (예: 토큰 만료) 등은 globa 영역에서의 handling을 통해서 관리되면 best 일 것 같습니다.
